"""
SportsGameOdds Stat Constants
Centralized registry for all supported stat IDs per sport.
Data source: SportsGameOdds API Documentation.
"""

# Special handling for 'points' per sport
SGO_POINTS_NAME = {
    "BASEBALL": "Runs",
    "BASKETBALL": "Points",
    "FOOTBALL": "Points",
    "GOLF": "To Par",
    "HOCKEY": "Goals",
    "MMA": "Fight Winner",
    "BOXING": "Fight Winner",
    "SOCCER": "Goals",
    "TENNIS": "Sets",
}

SGO_STATS = {
    "BASEBALL": {
        "points": "Runs",
        "fielding_assists": "Assists",
        "batting_atBats": "At Bats",
        "pitching_battersFaced": "Batters Faced",
        "batting_battingAvg": "Batting Average",
        "batting_caughtStealing": "Caught Stealing",
        "batting_doubles": "Doubles",
        "pitching_earnedRuns": "Earned Runs",
        "pitching_ERA": "ERA",
        "fielding_errors": "Errors",
        "fantasyScore": "Fantasy Score",
        "batting_firstHomeRun": "First Home Run",
        "firstToScore": "First Run",
        "batting_flyOuts": "Fly Outs",
        "batting_groundOuts": "Ground Outs",
        "batting_hitByPitch": "Hit by Pitch",
        "batting_hits": "Hits",
        "batting_hits+runs+rbi": "Hits + Runs + RBIs",
        "pitching_hits": "Hits Allowed",
        "batting_homeRuns": "Home Runs",
        "pitching_homeRunsAllowed": "Home Runs Allowed",
        "inningsInLead": "Innings in Lead",
        "pitching_inningsPitched": "Innings Pitched",
        "largestLead": "Largest Lead",
        "lastToScore": "Last Run",
        "leadChanges": "Lead Changes",
        "batting_leftOnBase": "Left on Base",
        "batting_onBasePercent": "On-Base %",
        "batting_OPS": "On-Base + Slugging %",
        "pitching_outs": "Outs",
        "pitching_pitchesThrown": "Pitches Thrown",
        "pitching_win": "Pitching Win",
        "fielding_putOuts": "Put Outs",
        "batting_runs+rbi": "Runs + RBIs",
        "pitching_runsAllowed": "Runs Allowed",
        "batting_RBI": "Runs Batted In",
        "batting_sacrificeBunts": "Sacrifice Bunts",
        "batting_sacrificeFlies": "Sacrifice Flies",
        "batting_singles": "Singles",
        "batting_sluggingPercent": "Slugging %",
        "batting_stolenBases": "Stolen Bases",
        "batting_strikeouts": "Strikeouts",
        "pitching_strikeouts": "Strikeouts",
        "pitching_strikesThrown": "Strikes Thrown",
        "timesTied": "Times Tied",
        "batting_totalBases": "Total Bases",
        "batting_triples": "Triples",
        "batting_basesOnBalls": "Walks",
        "pitching_basesOnBalls": "Walks",
    },
    "BASKETBALL": {
        "points": "Points",
        "assists": "Assists",
        "blocks": "Blocks",
        "blocks+steals": "Blocks + Steals",
        "defensiveRebounds": "Defensive Rebounds",
        "doubleDouble": "Double-Double",
        "fantasyScore": "Fantasy Score",
        "fastBreakPoints": "Fast Break Points",
        "fieldGoalPercent": "Field Goal Percentage",
        "fieldGoalsAttempted": "Field Goals Attempted",
        "fieldGoalsMade": "Field Goals Made",
        "firstBasket": "First Basket",
        "firstTo10": "First to 10",
        "firstTo100": "First to 100",
        "firstTo15": "First to 15",
        "firstTo20": "First to 20",
        "firstTo25": "First to 25",
        "firstTo50": "First to 50",
        "firstTo75": "First to 75",
        "firstToScore": "First to Score",
        "fouls": "Fouls Committed",
        "freeThrowPercent": "Free Throw Percentage",
        "freeThrowsAttempted": "Free Throws Attempted",
        "freeThrowsMade": "Free Throws Made",
        "largestLead": "Largest Lead",
        "leadChanges": "Lead Changes",
        "longestScoringRun": "Longest Scoring Run",
        "minutesInLead": "Minutes In Lead",
        "minutesPlayed": "Minutes Played",
        "offensiveRebounds": "Offensive Rebounds",
        "plusMinus": "Plus/Minus",
        "points+assists": "Points + Assists",
        "points+rebounds": "Points + Rebounds",
        "points+rebounds+assists": "Points + Rebounds + Assists",
        "pointsInPaint": "Points In The Paint",
        "pointsOffTurnovers": "Points Off Turnovers",
        "rebounds": "Rebounds",
        "rebounds+assists": "Rebounds + Assists",
        "secondChancePoints": "Second Chance Points",
        "secondsInLead": "Seconds In Lead",
        "secondsPlayed": "Seconds Played",
        "steals": "Steals",
        "threePointerPercent": "Three Pointer Percentage",
        "threePointersAttempted": "Three Pointers Attempted",
        "threePointersMade": "Three Pointers Made",
        "timesTied": "Times Tied",
        "tripleDouble": "Triple-Double",
        "turnovers": "Turnovers",
        "twoPointerPercent": "Two Pointer Percentage",
        "twoPointersAttempted": "Two Pointers Attempted",
        "twoPointersMade": "Two Pointers Made",
    },
    "FOOTBALL": {
        "points": "Points",
        "fieldGoals_1to19YardsMade": "1-19 Yard FGs Made",
        "fieldGoals_20to29YardsMade": "20-29 Yard FGs Made",
        "fieldGoals_30to39YardsMade": "30-39 Yard FGs Made",
        "fieldGoals_40to49YardsMade": "40-49 Yard FGs Made",
        "fieldGoals_50PlusYardsMade": "50+ Yard FGs Made",
        "defense_assistedTackles": "Assisted Tackles",
        "punting_puntsBlocked": "Blocked Punts",
        "defense_combinedTackles": "Combined Tackles + Assists",
        "defense_safeties": "Defensive Safeties",
        "offense_drives": "Drives",
        "extraPoints_kickAttempts": "Extra Point Attempts",
        "extraPoints_kicksMade": "Extra Points Made",
        "fantasyScore": "Fantasy Score",
        "fieldGoals_attempts": "Field Goal Attempts",
        "fieldGoals_attemptsBlocked": "Field Goal Attempts Blocked",
        "fieldGoalBlocks": "Field Goal Blocks",
        "fieldGoals_percentMade": "Field Goal Percentage",
        "fieldGoals_made": "Field Goals Made",
        "firstDowns": "First Downs",
        "firstTo10": "First to 10",
        "firstTo15": "First to 15",
        "firstTo20": "First to 20",
        "firstTo25": "First to 25",
        "firstToScore": "First to Score",
        "firstTouchdown": "First Touchdown",
        "offense_fourthDownAttempts": "Fourth Down Attempts",
        "offense_fourthDownConversions": "Fourth Down Conversions",
        "offense_fourthDownEfficiency": "Fourth Down Efficiency",
        "fumbles": "Fumbles",
        "defense_fumblesForced": "Fumbles Forced",
        "fumblesLost": "Fumbles Lost",
        "defense_fumblesRecovered": "Fumbles Recovered",
        "passing_interceptions": "Interceptions (Pass)",
        "defense_interceptions": "Interceptions (Def)",
        "kicking_totalPoints": "Kicking Total Points",
        "kickoffReturn_touchdowns": "Kickoff Return Touchdowns",
        "kickoffReturn_yards": "Kickoff Return Yards",
        "kickOffReturn_yardsPerReturn": "Kickoff Return Yards Per Return",
        "kickoffReturn_numReturns": "Kickoff Returns",
        "largestLead": "Largest Lead",
        "lastToScore": "Last Run",
        "lastTouchdown": "Last Touchdown",
        "leadChanges": "Lead Changes",
        "passing_longestCompletion": "Longest Completion",
        "fieldGoals_longestAttempt": "Longest Field Goal Attempt",
        "fieldGoals_longestMade": "Longest Field Goal Made",
        "kickoffReturn_longestReturn": "Longest Kickoff Return",
        "punting_longestPunt": "Longest Punt",
        "puntReturn_longestReturn": "Longest Punt Return",
        "receiving_longestReception": "Longest Reception",
        "rushing_longestRush": "Longest Rush",
        "longestScoringRun": "Longest Scoring Run",
        "minutesInLead": "Minutes In Lead",
        "punting_netYards": "Net Punting Yards",
        "passing_netYards": "Net Yards",
        "passing_twoPointConversions": "Pass Two Point Conversions",
        "passing_passerRating": "Passer Rating",
        "defense_passesDefended": "Passes Defended",
        "passing+rushing_yards": "Passing + Rushing Yards",
        "passing_attempts": "Passing Attempts",
        "passing_completions": "Passing Completions",
        "passing_firstDowns": "Passing First Downs",
        "passing_touchdowns": "Passing Touchdowns",
        "passing_yards": "Passing Yards",
        "penalty_count": "Penalties",
        "penalty_firstDowns": "Penalty First Downs",
        "penalty_yards": "Penalty Yards",
        "defense_pickSixes": "Pick Sixes",
        "offense_plays": "Plays",
        "puntBlocks": "Punt Blocks",
        "puntReturn_touchdowns": "Punt Return Touchdowns",
        "puntReturn_yards": "Punt Return Yards",
        "puntReturn_yardsPerReturn": "Punt Return Yards Per Return",
        "puntReturn_numReturns": "Punt Returns",
        "punting_yards": "Punting Yards",
        "punting_yardsPerPunt": "Punting Yards Per Punt",
        "punting_numPunts": "Punts",
        "punting_puntsForFairCatch": "Punts for Fair Catch",
        "punting_puntsForTouchback": "Punts for Touchback",
        "punting_puntsInside20": "Punts Inside 20",
        "defense_qbHits": "QB Hits",
        "receiving_firstDowns": "Receiving First Downs",
        "receiving_touchdowns": "Receiving Touchdowns",
        "receiving_yards": "Receiving Yards",
        "receiving_receptions": "Receptions",
        "offense_redZoneTouchdowns": "Red Zone Touchdowns",
        "offense_redZoneTrips": "Red Zone Trips",
        "rushing_yardsAfterContact": "Rush Yards After Contact",
        "rushing_yardsPerAttempt": "Rush Yards Per Attempt",
        "rushing+receiving_yards": "Rushing + Receiving Yards",
        "rushing_attempts": "Rushing Attempts",
        "rushing_firstDowns": "Rushing First Downs",
        "rushing_touchdowns": "Rushing Touchdowns",
        "rushing_twoPointConversions": "Rushing Two Point Conversions",
        "rushing_yards": "Rushing Yards",
        "passing_sackYards": "Sack Yards Lost",
        "defense_sacks": "Sacks",
        "passing_sacksTaken": "Sacks Taken",
        "defense_scoopAndScores": "Scoop and Scores",
        "secondsInLead": "Seconds In Lead",
        "defense_soloTackles": "Solo Tackles",
        "defense_tackles": "Tackles",
        "defense_tacklesForLoss": "Tackles for Loss",
        "receiving_targets": "Targets",
        "offense_thirdDownAttempts": "Third Down Attempts",
        "offense_thirdDownConversions": "Third Down Conversions",
        "offense_thirdDownEfficiency": "Third Down Efficiency",
        "offense_minutesOfPossession": "Time of Possession (Min.)",
        "offense_secondsOfPossession": "Time of Possession (Sec.)",
        "timesTied": "Times Tied",
        "touchdowns": "Touchdowns",
        "turnovers": "Turnovers",
        "receiving_twoPointConversions": "Two Point Conversions",
        "yards": "Yards",
        "receiving_yardsAfterCatch": "Yards After Catch",
        "passing_yardsPerAttempt": "Yards Per Attempt",
        "passing_yardsPerCompletion": "Yards Per Completion",
        "offense_yardsPerPlay": "Yards Per Play",
        "receiving_yardsPerReception": "Yards Per Reception",
    },
    "GOLF": {
        "points": "To Par",
        "birdiesOrBetter": "Birdies or Better",
        "parsOrBetter": "Pars or Better",
        "strokes": "Strokes",
    },
    "HOCKEY": {
        "points": "Goals",
        "assists": "Assists",
        "blocks": "Blocked Shots",
        "bothTeamsScored": "Both Teams Scored",
        "evenStrength_goals": "Even Strength Goals",
        "goalie_evenStrength_saves": "Even Strength Saves",
        "goalie_evenStrength_shotsAgainst": "Even Strength Shots Against",
        "evenStrength_assists": "Even-Strength Assists",
        "evenStrength_goals+assists": "Even-Strength Points",
        "faceOffs_lost": "Faceoffs Lost",
        "faceOffs_taken": "Faceoffs Taken",
        "faceOffs_won": "Faceoffs Won",
        "firstToScore": "First Goal",
        "giveaways": "Giveaways",
        "goalie_goalsAgainst": "Goals Against",
        "hits": "Hits",
        "largestLead": "Largest Lead",
        "lastToScore": "Last Goal",
        "leadChanges": "Lead Changes",
        "longestScoringRun": "Longest Scoring Run",
        "minutesInLead": "Minutes In Lead",
        "minutesPlayed": "Minutes Played",
        "penaltyMinutes": "Penalty Minutes",
        "penaltySeconds": "Penalty Seconds",
        "plusMinus": "Plus/Minus",
        "goals+assists": "Points (Goals + Assists)",
        "powerPlay_count": "Power Play Count",
        "goalie_powerPlay_saves": "Power Play Saves",
        "goalie_powerPlay_shotsAgainst": "Power Play Shots Against",
        "powerPlay_assists": "Power-Play Assists",
        "powerPlay_goals": "Power-Play Goals",
        "powerPlay_goals+assists": "Power-Play Points",
        "goalie_savePercent": "Save Percentage",
        "goalie_saves": "Saves",
        "secondsInLead": "Seconds In Lead",
        "secondsPlayed": "Seconds Played",
        "shortHanded_count": "Short Handed Count",
        "goalie_shortHanded_saves": "Short Handed Saves",
        "goalie_shortHanded_shotsAgainst": "Short Handed Shots Against",
        "shortHanded_assists": "Short-Handed Assists",
        "shortHanded_goals": "Short-Handed Goals",
        "shortHanded_goals+assists": "Short-Handed Points",
        "shots": "Shots",
        "goalie_shotsAgainst": "Shots Against",
        "shots_blocked": "Shots Blocked",
        "shots_offGoal": "Shots Off Goal",
        "shots_onGoal": "Shots On Goal",
        "shots_saved": "Shots Saved",
        "takeaways": "Takeaways",
        "timesTied": "Times Tied",
    },
    "MMA": {
        "points": "Fight Winner",
        "clinchControlTime_minutes": "Clinch Control Time (Minutes)",
        "clinchControlTime_seconds": "Clinch Control Time (seconds)",
        "clinchTime_minutes": "Clinch Time (Minutes)",
        "clinchTime_seconds": "Clinch Time (seconds)",
        "controlTime_minutes": "Control Time (Minutes)",
        "controlTime_seconds": "Control Time (seconds)",
        "fightTime_minutes": "Fight Time (Minutes)",
        "fightTime_seconds": "Fight Time (Seconds)",
        "groundTime_minutes": "Ground Time (Minutes)",
        "groundTime_seconds": "Ground Time (seconds)",
        "knockdowns": "Knockdowns",
        "roundsCompleted": "Rounds Completed",
        "significant_strike_attempts": "Significant Strike Attempts",
        "significant_strike_attempts_clinch": "Significant Strike Attempts from Clinch",
        "significant_strike_attempts_distance": "Significant Strike Attempts from Distance",
        "significant_strike_attempts_ground": "Significant Strike Attempts from Ground",
        "significant_strike_attempts_body": "Significant Strike Attempts to the Body",
        "significant_strike_attempts_head": "Significant Strike Attempts to the Head",
        "significant_strike_attempts_leg": "Significant Strike Attempts to the Leg",
        "significant_strikes": "Significant Strikes",
        "significant_strikes_distance": "Significant Strikes from Distance",
        "significant_strikes_clinch": "Significant Strikes in the Clinch",
        "significant_strikes_ground": "Significant Strikes on the Ground",
        "significant_strikes_body": "Significant Strikes to the Body",
        "significant_strikes_head": "Significant Strikes to the Head",
        "significant_strikes_leg": "Significant Strikes to the Leg",
        "strike_attempts": "Strike Attempts",
        "strikes": "Strikes",
        "strikes_body": "Strikes (Body)",
        "strikes_head": "Strikes (Head)",
        "strikes_leg": "Strikes (Leg)",
        "strike_attempts_body": "Strikes Attempted (Body)",
        "strike_attempts_head": "Strikes Attempted (Head)",
        "strike_attempts_leg": "Strikes Attempted (Leg)",
        "strike_attempts_clinch": "Strikes Attempted from Clinch",
        "strike_attempts_distance": "Strikes Attempted from Distance",
        "strike_attempts_ground": "Strikes Attempted from Ground",
        "strikes_distance": "Strikes from Distance",
        "strikes_clinch": "Strikes in the Clinch",
        "strikes_ground": "Strikes on the Ground",
        "submissions_attempted": "Submissions Attempted",
        "submissions_defended": "Submissions Defended",
        "takedown_attempts": "Takedown Attempts",
        "takedowns_defended": "Takedowns Defended",
        "takedowns_landed": "Takedowns Landed",
        "wonBy_decision": "Won by Decision",
        "wonBy_knockout": "Won by KO",
        "wonBy_submission": "Won by Submission",
    },
    "SOCCER": {
        "points": "Goals",
        "crosses_accurate": "Accurate Crosses",
        "longBalls_accurate": "Accurate Long Balls",
        "aerials_percent": "Aerial Win Percentage",
        "aerials_attempted": "Aerials Attempted",
        "aerials_lost": "Aerials Lost",
        "aerials_won": "Aerials Won",
        "assists": "Assists",
        "bothTeamsScored": "Both Teams Scored",
        "cardIndex": "Card Index",
        "combinedCards": "Cards",
        "weightedCards": "Cards (Weighted)",
        "clearances": "Clearances",
        "cornerKicks": "Corner Kicks",
        "crosses_percent": "Cross Accuracy",
        "crosses_attempted": "Crosses Attempted",
        "defense_dribbles_percent": "Defensive Dribble Win Percentage (Defense)",
        "defense_dribbles_contested": "Defensive Dribbles Contested",
        "defense_dribbles_lost": "Defensive Dribbles Lost",
        "defense_dribbles_won": "Defensive Dribbles Won",
        "disposed": "Dispossessed",
        "dribbles_percent": "Dribble Win Percentage",
        "dribbles_attempted": "Dribbles Attempted",
        "dribbles_lost": "Dribbles Lost",
        "dribbles_won": "Dribbles Won",
        "duels_percent": "Duel Win Percentage",
        "duels_attempted": "Duels Attempted",
        "duels_lost": "Duel Lost",
        "duels_won": "Duels Won",
        "firstToScore": "First Goal",
        "fouls": "Fouls Committed",
        "foulsDrawn": "Fouls Drawn",
        "freeKicks": "Free Kicks",
        "goalie_goalKicks": "Goal Kicks",
        "goals+assists": "Goals + Assists",
        "goalie_goalsAgainst": "Goals Against",
        "crosses_inaccurate": "Inaccurate Crosses",
        "longBalls_inaccurate": "Inaccurate Long Balls",
        "goalie_insideBox_saves": "Inside Box Saves",
        "interceptions": "Interceptions",
        "largestLead": "Largest Lead",
        "lastToScore": "Last Goal",
        "leadChanges": "Lead Changes",
        "longBalls_percent": "Long Ball Accuracy",
        "longBalls_attempted": "Long Balls Attempted",
        "longestScoringRun": "Longest Scoring Run",
        "minutesInLead": "Minutes In Lead",
        "minutesPlayed": "Minutes Played",
        "offsides": "Offsides",
        "passes_percent": "Pass Accuracy",
        "passes_accurate": "Passes Accurate",
        "passes_attempted": "Passes Attempted",
        "passes_inaccurate": "Passes Inaccurate",
        "penaltiesCommitted": "Penalties Committed",
        "penaltyKicks_percent": "Penalty Kick Accuracy",
        "penaltyKicks_made": "Penalty Kicks Made",
        "penaltyKicks_missed": "Penalty Kicks Missed",
        "goalie_penaltyKicksSaved": "Penalty Kicks Saved",
        "penaltyKicks_taken": "Penalty Kicks Taken",
        "playerRating": "Player Rating",
        "plusMinus": "Plus/Minus",
        "possessionPercent": "Possession Percentage",
        "redCards": "Red Cards",
        "goalie_savePercent": "Save Percentage",
        "goalie_saves": "Saves",
        "secondsInLead": "Seconds In Lead",
        "secondsPlayed": "Seconds Played",
        "shots": "Shots",
        "goalie_shotsAgainst": "Shots Against",
        "shots_assisted": "Shots Assisted",
        "shots_blocked": "Shots Blocked",
        "blocks": "Shots Blocked",
        "shots_hitCrossbar": "Shots Hit Crossbar",
        "shots_insideBox": "Shots Inside Box",
        "shots_offGoal": "Shots Off Goal",
        "shots_onGoal": "Shots On Goal",
        "shots_outsideBox": "Shots Outside Box",
        "shots_saved": "Shots Saved",
        "tackles": "Tackles",
        "throwIns": "Throw Ins",
        "timesTied": "Times Tied",
        "touches": "Touches",
        "yellowCards": "Yellow Cards",
    },
    "TENNIS": {
        "points": "Sets",
        "breakPoints": "Break Points Won",
        "fantasyScore": "Fantasy Score",
        "games": "Games",
        "serving_aces": "Serving Aces",
    }
}

def get_sgo_stat_display(sport_id: str, stat_id: str) -> str:
    """Get display name for an SGO stat ID tied to a sport."""
    sport_upper = sport_id.upper()
    if sport_upper in SGO_STATS and stat_id in SGO_STATS[sport_upper]:
        return SGO_STATS[sport_upper][stat_id]
        
    # Generic fallback
    if stat_id == "points":
        return SGO_POINTS_NAME.get(sport_upper, "Points")
        
    return stat_id.replace("_", " ").title()
