"""add picks playerstat historicalperformance tables

Revision ID: 744eb1c7924e
Revises: 0001
Create Date: 2026-01-28 08:05:04.677446+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744eb1c7924e'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_performances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=False),
    sa.Column('total_picks', sa.Integer(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('misses', sa.Integer(), nullable=False),
    sa.Column('hit_rate_percentage', sa.Float(), nullable=False),
    sa.Column('avg_ev', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=False),
    sa.Column('team', sa.String(length=100), nullable=False),
    sa.Column('opponent', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('stat_type', sa.String(length=50), nullable=False),
    sa.Column('actual_value', sa.Float(), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('picks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('pick_type', sa.String(length=50), nullable=False),
    sa.Column('player_name', sa.String(length=200), nullable=True),
    sa.Column('stat_type', sa.String(length=50), nullable=True),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('odds', sa.Integer(), nullable=False),
    sa.Column('model_probability', sa.Float(), nullable=False),
    sa.Column('implied_probability', sa.Float(), nullable=False),
    sa.Column('ev_percentage', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('hit_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('picks')
    op.drop_table('player_stats')
    op.drop_table('historical_performances')
    # ### end Alembic commands ###
