"""add bet_logs

Revision ID: 3009eef8390c
Revises: 80fb4068f184
Create Date: 2026-03-02 21:48:59.039692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3009eef8390c'
down_revision: Union[str, Sequence[str], None] = '80fb4068f184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('edge_config_history')
    op.drop_table('prop_history')
    op.drop_table('edge_config')
    op.drop_index(op.f('ix_markets_stat_type'), table_name='markets')
    op.create_index(op.f('ix_markets_stat_type'), 'markets', ['stat_type'], unique=False)
    op.add_column('model_picks', sa.Column('sport_key', sa.String(), nullable=True))
    op.add_column('model_picks', sa.Column('sport_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_model_picks_sport_id'), 'model_picks', ['sport_id'], unique=False)
    op.create_index(op.f('ix_model_picks_sport_key'), 'model_picks', ['sport_key'], unique=False)
    op.drop_column('model_picks', 'sport')
    op.alter_column('proplines', 'position',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('proplines', 'is_settled',
               existing_type=sa.BLOB(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_index(op.f('ix_proplines_game_id'), 'proplines', ['game_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proplines_game_id'), table_name='proplines')
    op.alter_column('proplines', 'is_settled',
               existing_type=sa.Boolean(),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.alter_column('proplines', 'position',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)
    op.add_column('model_picks', sa.Column('sport', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_model_picks_sport_key'), table_name='model_picks')
    op.drop_index(op.f('ix_model_picks_sport_id'), table_name='model_picks')
    op.drop_column('model_picks', 'sport_id')
    op.drop_column('model_picks', 'sport_key')
    op.drop_index(op.f('ix_markets_stat_type'), table_name='markets')
    op.create_index(op.f('ix_markets_stat_type'), 'markets', ['stat_type'], unique=1)
    op.create_table('edge_config',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('active_edge_model', sa.VARCHAR(length=20), server_default=sa.text("'baseline'"), nullable=True),
    sa.Column('min_ev_threshold', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('(2.0)'), nullable=True),
    sa.Column('max_ev_threshold', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('(40.0)'), nullable=True),
    sa.Column('min_confidence', sa.NUMERIC(precision=5, scale=4), server_default=sa.text('(0.55)'), nullable=True),
    sa.Column('max_edge_percent', sa.NUMERIC(precision=5, scale=2), server_default=sa.text('(30.0)'), nullable=True),
    sa.Column('min_line_value', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('(0.5)'), nullable=True),
    sa.Column('max_line_value', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('(999.0)'), nullable=True),
    sa.Column('min_odds', sa.INTEGER(), server_default=sa.text('(-300)'), nullable=True),
    sa.Column('max_odds', sa.INTEGER(), server_default=sa.text('(300)'), nullable=True),
    sa.Column('kelly_fraction', sa.NUMERIC(precision=4, scale=3), server_default=sa.text('(0.25)'), nullable=True),
    sa.Column('enabled_sports', sa.TEXT(), server_default=sa.text("'[30,31,1,2,53]'"), nullable=True),
    sa.Column('max_picks_per_game', sa.INTEGER(), server_default=sa.text('5'), nullable=True),
    sa.Column('max_parlays', sa.INTEGER(), server_default=sa.text('(10)'), nullable=True),
    sa.Column('sharp_money_threshold', sa.NUMERIC(precision=5, scale=4), server_default=sa.text('(0.65)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prop_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('prop_line_id', sa.INTEGER(), nullable=True),
    sa.Column('old_line', sa.FLOAT(), nullable=True),
    sa.Column('new_line', sa.FLOAT(), nullable=True),
    sa.Column('old_odds_over', sa.INTEGER(), nullable=True),
    sa.Column('new_odds_over', sa.INTEGER(), nullable=True),
    sa.Column('old_odds_under', sa.INTEGER(), nullable=True),
    sa.Column('new_odds_under', sa.INTEGER(), nullable=True),
    sa.Column('change_type', sa.VARCHAR(length=50), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['prop_line_id'], ['proplines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edge_config_history',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('config_id', sa.INTEGER(), nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=50), server_default=sa.text("'admin'"), nullable=True),
    sa.Column('change_summary', sa.TEXT(), nullable=True),
    sa.Column('previous_values', sa.TEXT(), nullable=True),
    sa.Column('new_values', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
