"""users_columns

Revision ID: 37ec23b25681
Revises: d704851d1e6b
Create Date: 2026-02-26 16:34:32.651682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '37ec23b25681'
down_revision: Union[str, Sequence[str], None] = 'd704851d1e6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publicslates', sa.Column('picks', sa.JSON(), nullable=True))
    op.add_column('publicslates', sa.Column('published_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('publicslates', sa.Column('created_by', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_publicslates_user_id'), table_name='publicslates')
    op.drop_column('publicslates', 'user_id')
    op.drop_column('publicslates', 'created_at')
    op.drop_column('publicslates', 'likes_count')
    op.drop_column('publicslates', 'copies_count')
    op.drop_column('publicslates', 'plays_json')
    op.add_column('users', sa.Column('discord_webhook_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_bot_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'telegram_bot_token')
    op.drop_column('users', 'discord_webhook_url')
    op.add_column('publicslates', sa.Column('plays_json', sqlite.JSON(), nullable=True))
    op.add_column('publicslates', sa.Column('copies_count', sa.INTEGER(), nullable=True))
    op.add_column('publicslates', sa.Column('likes_count', sa.INTEGER(), nullable=True))
    op.add_column('publicslates', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('publicslates', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_publicslates_user_id'), 'publicslates', ['user_id'], unique=False)
    op.drop_column('publicslates', 'created_by')
    op.drop_column('publicslates', 'published_at')
    op.drop_column('publicslates', 'picks')
    # ### end Alembic commands ###
