"""Add CLV enrichment columns to model_picks

Revision ID: 80fb4068f184
Revises: 37ec23b25681
Create Date: 2026-02-26 22:17:56.826234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80fb4068f184'
down_revision: Union[str, Sequence[str], None] = '37ec23b25681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apikeys', sa.Column('tier', sa.String(), nullable=True))
    op.add_column('apikeys', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('apikeys', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('apikeys', sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True))
    op.add_column('apikeys', sa.Column('requests_this_hour', sa.Integer(), nullable=True))
    op.add_column('apikeys', sa.Column('last_reset', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.add_column('apikeys', sa.Column('total_requests', sa.Integer(), nullable=True))
    op.add_column('apikeys', sa.Column('last_used', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('apikeys', 'requests_count')
    op.add_column('betlogs', sa.Column('clv', sa.Float(), nullable=True))
    op.add_column('betlogs', sa.Column('clv_label', sa.String(), nullable=True))
    op.add_column('proplines', sa.Column('hit_rate_l10', sa.Integer(), nullable=True))
    op.add_column('proplines', sa.Column('fatigue_flag', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proplines', 'fatigue_flag')
    op.drop_column('proplines', 'hit_rate_l10')
    op.drop_column('betlogs', 'clv_label')
    op.drop_column('betlogs', 'clv')
    op.add_column('apikeys', sa.Column('requests_count', sa.INTEGER(), nullable=True))
    op.drop_column('apikeys', 'last_used')
    op.drop_column('apikeys', 'total_requests')
    op.drop_column('apikeys', 'last_reset')
    op.drop_column('apikeys', 'requests_this_hour')
    op.drop_column('apikeys', 'rate_limit_per_hour')
    op.drop_column('apikeys', 'expires_at')
    op.drop_column('apikeys', 'is_active')
    op.drop_column('apikeys', 'tier')
    # ### end Alembic commands ###
