"""add_clv_and_legacy_tables

Revision ID: a60410aac577
Revises: ba1137c91a76
Create Date: 2026-03-08 06:32:27.685029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60410aac577'
down_revision: Union[str, Sequence[str], None] = 'ba1137c91a76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clv_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('bet_id', sa.Integer(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('opening_line', sa.Float(), nullable=True),
    sa.Column('closing_line', sa.Float(), nullable=True),
    sa.Column('clv', sa.Float(), nullable=True),
    sa.Column('clv_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clv_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clv_records_bet_id'), ['bet_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clv_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clv_records_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_clv_records_user_id'), ['user_id'], unique=False)

    op.create_table('steam_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('movement', sa.Float(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steam_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steam_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_steam_events_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_steam_events_sport'), ['sport'], unique=False)

    op.create_table('whale_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('amount_estimate', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('books_involved', sa.String(), nullable=True),
    sa.Column('whale_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whale_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whale_moves_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whale_moves_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_whale_moves_sport'), ['sport'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('whale_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whale_moves_sport'))
        batch_op.drop_index(batch_op.f('ix_whale_moves_player_name'))
        batch_op.drop_index(batch_op.f('ix_whale_moves_id'))

    op.drop_table('whale_moves')
    with op.batch_alter_table('steam_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steam_events_sport'))
        batch_op.drop_index(batch_op.f('ix_steam_events_player_name'))
        batch_op.drop_index(batch_op.f('ix_steam_events_id'))

    op.drop_table('steam_events')
    with op.batch_alter_table('clv_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clv_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_clv_records_player_name'))
        batch_op.drop_index(batch_op.f('ix_clv_records_id'))
        batch_op.drop_index(batch_op.f('ix_clv_records_bet_id'))

    op.drop_table('clv_records')
    # ### end Alembic commands ###
