"""add_analytical_tables_batch

Revision ID: ba1137c91a76
Revises: 3009eef8390c
Create Date: 2026-03-08 06:16:13.545019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba1137c91a76'
down_revision: Union[str, Sequence[str], None] = '3009eef8390c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('movement', sa.Float(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steam_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steam_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_steam_events_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_steam_events_sport'), ['sport'], unique=False)

    op.create_table('whale_moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('amount_estimate', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('books_involved', sa.String(), nullable=True),
    sa.Column('whale_label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whale_moves', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_whale_moves_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_whale_moves_player_name'), ['player_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_whale_moves_sport'), ['sport'], unique=False)

    op.drop_table('picks')
    with op.batch_alter_table('player_hit_rates', schema=None) as batch_op:
        batch_op.alter_column('player_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('stat_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.drop_column('total_picks')
        batch_op.drop_column('hits')
        batch_op.drop_column('hit_rate')

    with op.batch_alter_table('proplines', schema=None) as batch_op:
        batch_op.alter_column('actual_value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proplines', schema=None) as batch_op:
        batch_op.alter_column('actual_value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    with op.batch_alter_table('player_hit_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hit_rate', sa.REAL(), nullable=True))
        batch_op.add_column(sa.Column('hits', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('total_picks', sa.INTEGER(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('stat_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('player_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    op.create_table('picks',
    sa.Column('id', sa.TEXT(), nullable=True),
    sa.Column('user_id', sa.TEXT(), nullable=True),
    sa.Column('player_name', sa.TEXT(), nullable=True),
    sa.Column('team', sa.TEXT(), nullable=True),
    sa.Column('sport', sa.TEXT(), nullable=True),
    sa.Column('stat_type', sa.TEXT(), nullable=True),
    sa.Column('line', sa.REAL(), nullable=True),
    sa.Column('pick', sa.TEXT(), nullable=True),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('ev_percentage', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('whale_moves', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_whale_moves_sport'))
        batch_op.drop_index(batch_op.f('ix_whale_moves_player_name'))
        batch_op.drop_index(batch_op.f('ix_whale_moves_id'))

    op.drop_table('whale_moves')
    with op.batch_alter_table('steam_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steam_events_sport'))
        batch_op.drop_index(batch_op.f('ix_steam_events_player_name'))
        batch_op.drop_index(batch_op.f('ix_steam_events_id'))

    op.drop_table('steam_events')
    # ### end Alembic commands ###
