"""Initial schema

Revision ID: d704851d1e6b
Revises: 
Create Date: 2026-02-26 02:00:55.064396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd704851d1e6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikeys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('requests_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_apikeys_id'), 'apikeys', ['id'], unique=False)
    op.create_index(op.f('ix_apikeys_user_id'), 'apikeys', ['user_id'], unique=False)
    op.create_table('betlogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=True),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(), nullable=True),
    sa.Column('odds_taken', sa.Integer(), nullable=True),
    sa.Column('line_taken', sa.Float(), nullable=True),
    sa.Column('closing_odds', sa.Integer(), nullable=True),
    sa.Column('closing_line', sa.Float(), nullable=True),
    sa.Column('clv_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_betlogs_id'), 'betlogs', ['id'], unique=False)
    op.create_index(op.f('ix_betlogs_slip_id'), 'betlogs', ['slip_id'], unique=False)
    op.create_table('betslips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('slip_type', sa.String(), nullable=True),
    sa.Column('sportsbook', sa.String(), nullable=True),
    sa.Column('total_odds', sa.Integer(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_betslips_id'), 'betslips', ['id'], unique=False)
    op.create_index(op.f('ix_betslips_user_id'), 'betslips', ['user_id'], unique=False)
    op.create_table('contestentries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contestentries_contest_id'), 'contestentries', ['contest_id'], unique=False)
    op.create_index(op.f('ix_contestentries_id'), 'contestentries', ['id'], unique=False)
    op.create_index(op.f('ix_contestentries_user_id'), 'contestentries', ['user_id'], unique=False)
    op.create_table('contests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_fee', sa.Float(), nullable=True),
    sa.Column('prize_pool', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contests_id'), 'contests', ['id'], unique=False)
    op.create_table('kalshimarkets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('yes_price', sa.Float(), nullable=True),
    sa.Column('no_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('close_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kalshimarkets_id'), 'kalshimarkets', ['id'], unique=False)
    op.create_index(op.f('ix_kalshimarkets_ticker'), 'kalshimarkets', ['ticker'], unique=True)
    op.create_table('livegamestats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=True),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_livegamestats_game_id'), 'livegamestats', ['game_id'], unique=False)
    op.create_index(op.f('ix_livegamestats_id'), 'livegamestats', ['id'], unique=False)
    op.create_index(op.f('ix_livegamestats_player_id'), 'livegamestats', ['player_id'], unique=False)
    op.create_table('oddsalerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oddsalerts_id'), 'oddsalerts', ['id'], unique=False)
    op.create_index(op.f('ix_oddsalerts_prop_id'), 'oddsalerts', ['prop_id'], unique=False)
    op.create_table('playerstats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proplines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=True),
    sa.Column('player_name', sa.String(), nullable=True),
    sa.Column('team', sa.String(), nullable=True),
    sa.Column('opponent', sa.String(), nullable=True),
    sa.Column('sport_key', sa.String(), nullable=True),
    sa.Column('stat_type', sa.String(), nullable=True),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proplines_id'), 'proplines', ['id'], unique=False)
    op.create_index(op.f('ix_proplines_player_id'), 'proplines', ['player_id'], unique=False)
    op.create_index(op.f('ix_proplines_sport_key'), 'proplines', ['sport_key'], unique=False)
    op.create_table('propodds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_line_id', sa.Integer(), nullable=True),
    sa.Column('sportsbook', sa.String(), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('ev_percent', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propodds_id'), 'propodds', ['id'], unique=False)
    op.create_index(op.f('ix_propodds_sportsbook'), 'propodds', ['sportsbook'], unique=False)
    op.create_table('publicslates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plays_json', sa.JSON(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('copies_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_publicslates_id'), 'publicslates', ['id'], unique=False)
    op.create_index(op.f('ix_publicslates_user_id'), 'publicslates', ['user_id'], unique=False)
    op.create_table('pushsubscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=True),
    sa.Column('p256dh', sa.String(), nullable=True),
    sa.Column('auth', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_pushsubscriptions_id'), 'pushsubscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_pushsubscriptions_user_id'), 'pushsubscriptions', ['user_id'], unique=False)
    op.create_table('refereegame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('subscription_tier', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('lifetime_roi', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('picks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('game_id', sa.TEXT(), nullable=True),
    sa.Column('player_name', sa.TEXT(), nullable=True),
    sa.Column('stat_type', sa.TEXT(), nullable=True),
    sa.Column('line', sa.REAL(), nullable=True),
    sa.Column('side', sa.TEXT(), nullable=True),
    sa.Column('odds', sa.REAL(), nullable=True),
    sa.Column('ev_percentage', sa.REAL(), nullable=True),
    sa.Column('confidence', sa.REAL(), nullable=True),
    sa.Column('hit_rate', sa.REAL(), nullable=True),
    sa.Column('sportsbook', sa.TEXT(), nullable=True),
    sa.Column('sport', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('won', sa.BOOLEAN(), nullable=True),
    sa.Column('actual_value', sa.REAL(), nullable=True),
    sa.Column('profit_loss', sa.REAL(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('pick_type', sa.TEXT(), nullable=True),
    sa.Column('team', sa.TEXT(), nullable=True),
    sa.Column('model_probability', sa.REAL(), nullable=True),
    sa.Column('implied_probability', sa.REAL(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('schedule')
    op.drop_table('referral')
    op.drop_table('refereegame')
    op.drop_index(op.f('ix_pushsubscriptions_user_id'), table_name='pushsubscriptions')
    op.drop_index(op.f('ix_pushsubscriptions_id'), table_name='pushsubscriptions')
    op.drop_table('pushsubscriptions')
    op.drop_index(op.f('ix_publicslates_user_id'), table_name='publicslates')
    op.drop_index(op.f('ix_publicslates_id'), table_name='publicslates')
    op.drop_table('publicslates')
    op.drop_index(op.f('ix_propodds_sportsbook'), table_name='propodds')
    op.drop_index(op.f('ix_propodds_id'), table_name='propodds')
    op.drop_table('propodds')
    op.drop_index(op.f('ix_proplines_sport_key'), table_name='proplines')
    op.drop_index(op.f('ix_proplines_player_id'), table_name='proplines')
    op.drop_index(op.f('ix_proplines_id'), table_name='proplines')
    op.drop_table('proplines')
    op.drop_table('playerstats')
    op.drop_index(op.f('ix_oddsalerts_prop_id'), table_name='oddsalerts')
    op.drop_index(op.f('ix_oddsalerts_id'), table_name='oddsalerts')
    op.drop_table('oddsalerts')
    op.drop_index(op.f('ix_livegamestats_player_id'), table_name='livegamestats')
    op.drop_index(op.f('ix_livegamestats_id'), table_name='livegamestats')
    op.drop_index(op.f('ix_livegamestats_game_id'), table_name='livegamestats')
    op.drop_table('livegamestats')
    op.drop_index(op.f('ix_kalshimarkets_ticker'), table_name='kalshimarkets')
    op.drop_index(op.f('ix_kalshimarkets_id'), table_name='kalshimarkets')
    op.drop_table('kalshimarkets')
    op.drop_index(op.f('ix_contests_id'), table_name='contests')
    op.drop_table('contests')
    op.drop_index(op.f('ix_contestentries_user_id'), table_name='contestentries')
    op.drop_index(op.f('ix_contestentries_id'), table_name='contestentries')
    op.drop_index(op.f('ix_contestentries_contest_id'), table_name='contestentries')
    op.drop_table('contestentries')
    op.drop_index(op.f('ix_betslips_user_id'), table_name='betslips')
    op.drop_index(op.f('ix_betslips_id'), table_name='betslips')
    op.drop_table('betslips')
    op.drop_index(op.f('ix_betlogs_slip_id'), table_name='betlogs')
    op.drop_index(op.f('ix_betlogs_id'), table_name='betlogs')
    op.drop_table('betlogs')
    op.drop_index(op.f('ix_apikeys_user_id'), table_name='apikeys')
    op.drop_index(op.f('ix_apikeys_id'), table_name='apikeys')
    op.drop_table('apikeys')
    # ### end Alembic commands ###
